import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        tertiary: "#7bd0ff",
        "on-tertiary": "#00354a",
        "primary-fixed-dim": "#abc7ff",
        "secondary-fixed": "#e1e0ff",
        "surface-container-highest": "#273647",
        "on-surface": "#d4e4fa",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "secondary-container": "#3131c0",
        "tertiary-container": "#007ca8",
        "on-secondary": "#1000a9",
        "surface-container-lowest": "#010f1f",
        "on-surface-variant": "#c1c6d6",
        "on-primary": "#002f66",
        "text-faint": "#64748B",
        secondary: "#c0c1ff",
        primary: "#abc7ff",
        "canvas-deep": "#070A0F",
        "text-muted": "#94A3B8",
        "canvas-surface": "#0B0F17",
        "ios-purple": "#6366F1",
        surface: "#051424",
        "primary-container": "#0071e3",
        "surface-container-high": "#1c2b3c",
        "surface-container": "#0F172A",
        "pure-white": "#FFFFFF",
        "on-secondary-container": "#b0b2ff",
        "outline-variant": "#414753",
        "on-primary-container": "#fcfbff",
        "surface-variant": "#273647",
        "electric-blue": "#0071E3",
        "surface-container-low": "#0d1c2d",
        "surface-bright": "#2c3a4c",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-code": ["Geist", "ui-monospace", "monospace"],
        "label-badge": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        display: ["64px", { lineHeight: "72px", letterSpacing: "-0.035em", fontWeight: "700" }],
        "display-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-code": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
      },
      maxWidth: {
        content: "80rem",
      },
    },
  },
  plugins: [],
};

export default config;
